"""
Learned preferences: what your own decisions say you want, as a reviewable draft.

The fit judge reads me/profile.md and your resume - what you SAY you want. This
reads what you DO: the roles you closed with a reason that is about the role
itself (store.PREFERENCE_CLOSE_REASONS), and the roles you pursued (researching,
applied, or heard back from an employer). It never learns from a close without
a reason, or from a neutral one ("Chose another role at org", "Posting closed"):
those say nothing about what you want.

Two halves, deliberately split:
  - Python computes the evidence: per industry, function, level and category,
    how often you passed vs pursued against your overall rate, and where the
    model's recommendation and your decision disagreed. Only groups with at
    least MIN_DECISIONS decisions and a clear lean become candidates.
  - One LLM call reads the candidates with a few of your notes, drops the ones
    that are confounded or already covered by another, and phrases the rest as
    guidance for the fit judge. The counts in the output are attached here, from
    the evidence, never taken from the model.

The result is a DRAFT (me/learned.draft.md). Nothing reaches the fit prompt
until you approve it into me/learned.md - with --approve, or by editing and
saving it yourself. me/learned.md is yours: this module never overwrites it
except through --approve, which keeps the previous copy as learned.prev.md.

    uv run agents/preferences.py              # write a fresh draft
    uv run agents/preferences.py --evidence   # print the evidence, no LLM call
    uv run agents/preferences.py --approve    # promote the draft
"""
import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from llm import LLM, LLMError, output_budget           # noqa: E402
from store import PREFERENCE_CLOSE_REASONS, Store      # noqa: E402

DRAFT = "me/learned.draft.md"
LEARNED = "me/learned.md"
PREVIOUS = "me/learned.prev.md"

# Only decisions made inside this window count; tastes move.
WINDOW_DAYS = 180

# A group needs this many decisions before it can say anything at all.
MIN_DECISIONS = 5
# ...and this many on the side it leans toward.
MIN_LEANING = 4
# Pursue rates are shrunk toward your overall rate by this many pseudo-decisions,
# so five decisions cannot look like certainty.
PRIOR_STRENGTH = 4
# How far a group's shrunk pursue rate must sit from your overall rate to lean.
AVOID_RATIO = 0.6
SEEK_RATIO = 1.5
# A leaning group becomes a candidate only when you overrode the model on at
# least this many of its roles, AND on at least this share of the decisions on
# the side it leans to. A pattern the model already follows (you closed what it
# said to skip) teaches it nothing and only lengthens the prompt - and in a big
# group, a couple of overrides among ninety agreements is still agreement.
MIN_DISAGREEMENTS = 2
MIN_DISAGREEMENT_SHARE = 0.2

# A draft is regenerated by the daily run once the last one is this old.
DRAFT_INTERVAL_DAYS = 7

NOTES_PER_CANDIDATE = 5
# Output budget per candidate verdict: id, keep, and a one-sentence statement or
# a short why_dropped. The 4096 default cut the answer off at 19 candidates (over
# 200 tokens each), so this allows about twice that.
VERDICT_TOKENS_PER_CANDIDATE = 400
VERDICT_TOKENS_OVERHEAD = 500

PURSUED_STATUSES = {"02 Researching", "03 Applied"}

# An employer outcome on a role means you applied to it.
_NOT_AN_APPLICATION = {"", "closed"}

# Title level, most senior first; the first pattern that matches wins.
_LEVELS = [
    ("VP and above", re.compile(r"\b(vp|vice president|chief|head of|svp|evp|cxo|c[dt]o)\b", re.I)),
    ("Director", re.compile(r"\bdirector\b", re.I)),
    ("Principal / Staff / Lead", re.compile(r"\b(principal|staff|lead)\b", re.I)),
    ("Manager", re.compile(r"\bmanager\b", re.I)),
    ("Junior", re.compile(r"\b(associate|junior|jr\.?|intern|internship|ii|analyst)\b", re.I)),
    ("Senior IC", re.compile(r"\b(senior|sr\.?)\b", re.I)),
]


def title_level(title):
    for label, pattern in _LEVELS:
        if pattern.search(title or ""):
            return label
    return UNSPECIFIED_LEVEL


UNSPECIFIED_LEVEL = "Unspecified level"


def industry(sector):
    """"Finance - Banking" -> "Finance". Unknown and blank are not an industry."""
    head = (sector or "").split(" - ")[0].strip()
    return head if head and head.lower() != "unknown" else None


# ---------------------------------------------------------------------------
# evidence
# ---------------------------------------------------------------------------

def decision_of(row):
    """"passed", "pursued", or None when the row says nothing about you."""
    if row["status"] in PURSUED_STATUSES:
        return "pursued"
    if (row["outcomes"] or "").strip().lower() not in _NOT_AN_APPLICATION:
        return "pursued"
    if row["status"] == "04 Closed" and row["close_reason"] in PREFERENCE_CLOSE_REASONS:
        return "passed"
    return None


def recommendation_at(history, when, current):
    """What the model recommended at `when`, from the role's logged
    recommendation changes [(ts, old, new), ...] in time order.

    The first change AFTER the decision still carries, as its old value, what
    the model was saying when you decided. With no later change, the current
    value has held since before the decision."""
    for ts, old, _new in history:
        if when and ts > when:
            return old
    return current


def load_decisions(store, now=None, window_days=WINDOW_DAYS):
    """Every role you made a preference-bearing decision on, inside the window.

    A decision is dated by the last time YOU changed its status; failing that,
    the last time you touched its close reason or outcome; failing that, the
    row's own last update.

    Each decision carries the model's recommendation AT THAT TIME, not today's.
    Today's is shaped by the learned preferences themselves - once a pattern is
    learned the model agrees with you, and judging agreement against that would
    make every learned pattern erase itself on the next draft."""
    now = now or datetime.now()
    cutoff = (now - timedelta(days=window_days)).isoformat(timespec="seconds")
    with store.connect() as conn:
        status_ts = {r["role_id"]: r["ts"] for r in conn.execute(
            "SELECT role_id, MAX(ts) ts FROM changes WHERE field='status' "
            "AND actor NOT IN ('pipeline','migration') GROUP BY role_id")}
        touched = {r["role_id"]: r["ts"] for r in conn.execute(
            "SELECT role_id, MAX(ts) ts FROM changes "
            "WHERE field IN ('status','close_reason','outcomes') AND actor != 'pipeline' "
            "GROUP BY role_id")}
        rec_history = {}
        for r in conn.execute("SELECT role_id, ts, old_value, new_value FROM changes "
                              "WHERE field='recommendation' ORDER BY ts, seq"):
            rec_history.setdefault(r["role_id"], []).append((r["ts"], r["old_value"], r["new_value"]))
        rows = [dict(r) for r in conn.execute("SELECT * FROM roles")]

    decisions = []
    for row in rows:
        kind = decision_of(row)
        if not kind:
            continue
        when = status_ts.get(row["id"]) or touched.get(row["id"]) or row.get("updated_at") or ""
        if when and when < cutoff:
            continue
        decisions.append({
            "id": row["id"], "org": row["org"], "title": row["title"],
            "decision": kind, "reason": row["close_reason"] if kind == "passed" else None,
            "notes": (row["notes"] or "").strip(),
            "decided_at": when,
            "recommendation": recommendation_at(rec_history.get(row["id"], []), when,
                                                row["recommendation"]),
            "fit_score": row["fit_score"],
            "industry": industry(row["sector"]),
            "function": row["role_function"],
            "level": title_level(row["title"]),
            "category": row["role_cat"],
        })
    return decisions


DIMENSIONS = [("industry", "Employer industry"), ("function", "Function"),
              ("level", "Title level"), ("category", "Your role category")]


def _group_stats(items, base_rate):
    passed = [d for d in items if d["decision"] == "passed"]
    pursued = [d for d in items if d["decision"] == "pursued"]
    n = len(items)
    shrunk = (len(pursued) + PRIOR_STRENGTH * base_rate) / (n + PRIOR_STRENGTH)
    reasons = {}
    for d in passed:
        reasons[d["reason"]] = reasons.get(d["reason"], 0) + 1
    return {
        "decisions": n, "passed": len(passed), "pursued": len(pursued),
        "pursue_rate": round(len(pursued) / n, 2) if n else None,
        "shrunk_rate": round(shrunk, 2),
        "pass_reasons": dict(sorted(reasons.items(), key=lambda kv: -kv[1])),
        # Where you and the model disagreed - what the fit judge most needs to hear.
        "passed_though_model_liked": sum(
            1 for d in passed if d["recommendation"] in ("apply", "research")),
        "pursued_though_model_skipped": sum(
            1 for d in pursued if d["recommendation"] == "skip"),
    }


def _lean(stats, base_rate):
    if stats["decisions"] < MIN_DECISIONS:
        return None
    if stats["passed"] >= MIN_LEANING and stats["shrunk_rate"] <= base_rate * AVOID_RATIO:
        return "avoid"
    if stats["pursued"] >= MIN_LEANING and stats["shrunk_rate"] >= min(0.95, base_rate * SEEK_RATIO):
        return "seek"
    return None


def build_evidence(decisions):
    """Baseline plus the candidate patterns - groups with enough decisions and
    a clear lean away from your overall pursue rate."""
    n = len(decisions)
    pursued = sum(1 for d in decisions if d["decision"] == "pursued")
    base_rate = pursued / n if n else 0.0
    evidence = {"decisions": n, "passed": n - pursued, "pursued": pursued,
                "base_pursue_rate": round(base_rate, 2), "candidates": [], "agreed": []}
    if not n:
        return evidence

    groups = {}
    for d in decisions:
        for dim, _label in DIMENSIONS:
            # "No level word in the title" is the matcher's leftover, not a group.
            if d.get(dim) and d[dim] != UNSPECIFIED_LEVEL:
                groups.setdefault((dim, d[dim]), []).append(d)
        # One cross: industry x function is where "passes on banks" and
        # "passes on finance work" come apart.
        if d.get("industry") and d.get("function"):
            groups.setdefault(("industry x function", f"{d['function']} at {d['industry']}"),
                              []).append(d)

    for (dim, value), items in sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        stats = _group_stats(items, base_rate)
        lean = _lean(stats, base_rate)
        if not lean:
            continue
        overrides = (stats["passed_though_model_liked"] if lean == "avoid"
                     else stats["pursued_though_model_skipped"])
        leaning = stats["passed"] if lean == "avoid" else stats["pursued"]
        if overrides < MIN_DISAGREEMENTS or overrides < MIN_DISAGREEMENT_SHARE * leaning:
            # Real pattern, but the model was already making the same call.
            evidence["agreed"].append({"dimension": dim, "value": value, "lean": lean, **stats})
            continue
        side = "passed" if lean == "avoid" else "pursued"
        notes = [f"{d['title']} @ {d['org']}: {d['notes'][:160]}"
                 for d in items if d["decision"] == side and d["notes"]][:NOTES_PER_CANDIDATE]
        evidence["candidates"].append({
            "id": f"c{len(evidence['candidates']) + 1}", "dimension": dim, "value": value,
            "lean": lean, **stats, "sample_notes": notes,
        })
    return evidence


# ---------------------------------------------------------------------------
# draft
# ---------------------------------------------------------------------------

def _prompt(evidence, profile_text):
    return f"""You maintain a short "learned preferences" note that a job-fit judge reads
next to the candidate's stated profile. It is built ONLY from what the candidate
actually did: roles they passed on for a stated reason, and roles they pursued.

THE CANDIDATE'S STATED PROFILE (for context - do not restate it):
{profile_text[:3000]}

OVERALL: {evidence['decisions']} decisions, {evidence['pursued']} pursued, \
{evidence['passed']} passed. Base pursue rate {evidence['base_pursue_rate']}.

CANDIDATE PATTERNS (each clears a minimum-evidence bar, and in each the candidate
overrode the model's recommendation at the time more than once - these are the
corrections the judge needs):
{json.dumps(evidence['candidates'], indent=2)}

For each candidate decide keep or drop, then write one statement for each kept one.

RULES:
  - Drop a candidate that another candidate explains better. If "Data Science & ML
    at Finance" and "Finance" both lean avoid, and the notes cite industry, keep the
    industry one and drop the narrower one - or the reverse if the evidence says so.
    Never keep two statements that say the same thing.
  - Drop a candidate whose lean is plausibly a side effect of something else
    (a level or location problem showing up as an industry pattern). Say why.
  - Drop a candidate that the stated profile already says plainly; the judge has
    that. Keep one that sharpens or contradicts the profile - those matter most.
  - A statement is ONE sentence of guidance to the fit judge, concrete, in the
    candidate's terms: "Treat roles at banks, insurers and asset managers as a
    weak fit whatever the function - the candidate passes on them for industry
    reasons." No counts or percentages - those are attached separately.
  - Use the sample notes to name WHY when they say so. Do not invent a reason.
  - Keeping nothing is a correct answer when nothing is clear.

Return ONLY a JSON array, one object per candidate id:
[{{"id": "<candidate id>", "keep": true | false,
   "statement": "<one sentence, when kept>", "why_dropped": "<short clause, when dropped>"}}]"""


def make_validator(evidence):
    ids = {c["id"] for c in evidence["candidates"]}

    def validate(data):
        if not isinstance(data, list) or not data:
            return False
        for item in data:
            if not isinstance(item, dict) or item.get("id") not in ids:
                return False
            if not isinstance(item.get("keep"), bool):
                return False
            if item["keep"] and not (isinstance(item.get("statement"), str)
                                     and item["statement"].strip()):
                return False
        return True

    return validate


def _evidence_line(c):
    reasons = ", ".join(f"{k.lower()} {v}" for k, v in c["pass_reasons"].items())
    line = (f"{c['dimension']} = {c['value']}: passed {c['passed']}, "
            f"pursued {c['pursued']} of {c['decisions']}")
    if reasons:
        line += f" (passed for: {reasons})"
    if c["passed_though_model_liked"]:
        line += f"; passed on {c['passed_though_model_liked']} the model rated apply/research"
    if c["pursued_though_model_skipped"]:
        line += f"; pursued {c['pursued_though_model_skipped']} the model said to skip"
    return line


def render_draft(evidence, verdicts, now=None):
    now = now or datetime.now()
    by_id = {c["id"]: c for c in evidence["candidates"]}
    kept = [(by_id[v["id"]], v) for v in verdicts if v.get("keep") and v["id"] in by_id]
    dropped = [(by_id[v["id"]], v) for v in verdicts if not v.get("keep") and v["id"] in by_id]

    lines = [
        "# Learned preferences",
        "",
        f"<!-- DRAFT generated {now:%Y-%m-%d} from {evidence['decisions']} decisions in the last",
        f"     {WINDOW_DAYS} days ({evidence['pursued']} pursued, {evidence['passed']} passed for a reason",
        "     about the role). Nothing here is used until it is saved as me/learned.md:",
        "         uv run agents/preferences.py --approve",
        "     Edit freely first - delete a line you disagree with, reword one that is off.",
        "     The fit judge reads the bullet text; these comments are stripped. -->",
        "",
    ]
    for lean, heading in (("avoid", "Weigh down"), ("seek", "Weigh up")):
        items = [(c, v) for c, v in kept if c["lean"] == lean]
        if not items:
            continue
        lines += [f"## {heading}", ""]
        for c, v in items:
            lines.append(f"- {v['statement'].strip()}")
            lines.append(f"  <!-- evidence: {_evidence_line(c)} -->")
        lines.append("")
    if not kept:
        lines += ["_No clear pattern in your decisions yet._", ""]
    if evidence.get("agreed"):
        lines.append("<!-- real patterns the model already follows, so left out:")
        for c in evidence["agreed"]:
            lines.append(f"     - {c['dimension']} = {c['value']} ({c['lean']}): "
                         f"passed {c['passed']}, pursued {c['pursued']} of {c['decisions']}")
        lines.append("-->")
    if dropped:
        lines.append("<!-- considered and dropped:")
        for c, v in dropped:
            lines.append(f"     - {c['dimension']} = {c['value']} ({c['lean']}): "
                         f"{(v.get('why_dropped') or 'no reason given').strip()}")
        lines.append("-->")
    return "\n".join(lines).rstrip() + "\n"


def write_draft(base_dir, llm=None, now=None):
    """Build the evidence, ask for a verdict on each candidate, write the draft.
    Returns the draft path, or None when there is nothing to write."""
    base_dir = Path(base_dir)
    evidence = build_evidence(load_decisions(Store(base_dir), now=now))
    print(f"  preferences: {evidence['decisions']} decision(s), "
          f"{len(evidence['candidates'])} candidate pattern(s), "
          f"{len(evidence['agreed'])} the model already follows")
    if not evidence["candidates"]:
        verdicts = []
    else:
        profile = base_dir / "me/profile.md"
        llm = llm or LLM(base_dir)
        try:
            verdicts = llm.complete_json(
                _prompt(evidence, profile.read_text() if profile.exists() else ""),
                tag="preferences", validate=make_validator(evidence),
                max_tokens=output_budget(len(evidence["candidates"]),
                                         per_item=VERDICT_TOKENS_PER_CANDIDATE,
                                         overhead=VERDICT_TOKENS_OVERHEAD))
        except LLMError as exc:
            print(f"  ! preferences draft failed, previous draft kept: {exc}")
            return None
    path = base_dir / DRAFT
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_draft(evidence, verdicts, now=now))
    print(f"  preferences draft -> {path.relative_to(base_dir)}")
    return path


def draft_is_due(base_dir, now=None):
    path = Path(base_dir) / DRAFT
    if not path.exists():
        return True, "no draft yet"
    age = ((now or datetime.now()) - datetime.fromtimestamp(path.stat().st_mtime)).days
    if age >= DRAFT_INTERVAL_DAYS:
        return True, f"{age}d since last draft"
    return False, f"{DRAFT_INTERVAL_DAYS - age}d until next draft"


def approve(base_dir):
    """Promote the draft to me/learned.md, keeping the previous copy."""
    base_dir = Path(base_dir)
    draft, learned = base_dir / DRAFT, base_dir / LEARNED
    if not draft.exists():
        raise FileNotFoundError(f"no draft at {DRAFT} - run preferences.py first")
    if learned.exists():
        shutil.copy2(learned, base_dir / PREVIOUS)
    shutil.copy2(draft, learned)
    return learned


def main(argv=None):
    import workspace
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    workspace.add_argument(ap)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--evidence", action="store_true",
                      help="print the evidence and candidate patterns, no LLM call")
    mode.add_argument("--approve", action="store_true",
                      help=f"promote {DRAFT} to {LEARNED}")
    args = ap.parse_args(argv)
    base = workspace.resolve(args.user)

    if args.approve:
        print(f"approved -> {approve(base).relative_to(base)}")
        return 0
    if args.evidence:
        print(json.dumps(build_evidence(load_decisions(Store(base))), indent=2))
        return 0
    return 0 if write_draft(base) else 1


if __name__ == "__main__":
    sys.exit(main())
